apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-circle-1
  namespace: default
  labels:
    app: backend-circle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-circle
  template:
    metadata:
      labels:
        app: backend-circle
    spec:
      containers:
        - name: infra-backend
          image: nginx
          ports:
            - containerPort: 80