apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circle-app
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./declarative/manifests/circle
    repoURL: https://github.com/Jay179-sudo/App-of-Apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources: []
  project: default
