apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: square-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 60.0.1
    helm:
      releaseName: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources: []
  project: default
